import type { StepDef } from "./types";

/**
 * Default workflows (brief 6.5), used by the seed and as the reference
 * shape in tests. `id` values are stable codes; the seed maps them to
 * real workflow_steps rows.
 */
export const defaultSignageSteps: StepDef[] = [
  // Department sign-offs: Operations, Marketing and (for sponsor signage)
  // Sales review together, then Senior management. Each item can switch
  // departments on or off and name the person in each.
  {
    id: "sig-ops",
    sortOrder: 1,
    parallelGroup: 1,
    name: "Operations sign-off",
    kind: "approval",
    approverType: "role",
    approverRole: "ops",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 3,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
    defaultFor: ["organiser", "sponsor"],
  },
  {
    id: "sig-marketing",
    sortOrder: 2,
    parallelGroup: 1,
    name: "Marketing sign-off",
    kind: "approval",
    approverType: "role",
    approverRole: "marketing",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 3,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
    defaultFor: ["organiser", "sponsor"],
  },
  {
    id: "sig-sales",
    sortOrder: 3,
    parallelGroup: 1,
    name: "Sales sign-off",
    kind: "approval",
    approverType: "role",
    approverRole: "sales",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 5,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
    defaultFor: ["sponsor"],
  },
  {
    id: "sig-venue",
    sortOrder: 4,
    parallelGroup: null,
    name: "Venue approval",
    kind: "approval",
    approverType: "role",
    approverRole: "venue",
    approverUserId: null,
    conditions: ["if_requires_venue_approval"],
    slaDays: 7,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
  },
  {
    id: "sig-senior",
    sortOrder: 5,
    parallelGroup: null,
    name: "Senior management sign-off",
    kind: "approval",
    approverType: "role",
    approverRole: "event_director",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 3,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
    defaultFor: ["organiser", "sponsor"],
  },
  {
    id: "sig-print",
    sortOrder: 6,
    parallelGroup: null,
    name: "Sent to print",
    kind: "confirmation",
    approverType: "role",
    approverRole: "supplier",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 2,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
  },
  {
    id: "sig-delivered",
    sortOrder: 7,
    parallelGroup: null,
    name: "Delivered",
    kind: "confirmation",
    approverType: "role",
    approverRole: "supplier",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 0,
    invalidateOnNewVersion: false,
    restartFromHereOnChanges: true,
  },
  {
    id: "sig-installed",
    sortOrder: 8,
    parallelGroup: null,
    name: "Installed",
    kind: "confirmation",
    approverType: "role",
    approverRole: "ops",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 0,
    invalidateOnNewVersion: false,
    restartFromHereOnChanges: true,
  },
];

export const defaultStandSteps: StepDef[] = [
  {
    id: "std-completeness",
    sortOrder: 1,
    parallelGroup: null,
    name: "Ops completeness and rules check",
    kind: "approval",
    approverType: "role",
    approverRole: "ops",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 3,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
  },
  {
    id: "std-engineer",
    sortOrder: 2,
    parallelGroup: null,
    name: "Structural engineer review",
    kind: "approval",
    approverType: "role",
    approverRole: "structural_engineer",
    approverUserId: null,
    conditions: ["if_complex_structure"],
    slaDays: 7,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
  },
  {
    id: "std-hs",
    sortOrder: 3,
    parallelGroup: null,
    name: "H&S review (RAMS, insurance)",
    kind: "approval",
    approverType: "role",
    approverRole: "hs",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 5,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
  },
  {
    id: "std-venue",
    sortOrder: 4,
    parallelGroup: null,
    name: "Venue approval",
    kind: "approval",
    approverType: "role",
    approverRole: "venue",
    approverUserId: null,
    conditions: ["if_venue_requires_stand_approval"],
    slaDays: 7,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
  },
  {
    id: "std-outcome",
    sortOrder: 5,
    parallelGroup: null,
    name: "Ops final outcome",
    kind: "approval",
    approverType: "role",
    approverRole: "ops",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 2,
    invalidateOnNewVersion: true,
    restartFromHereOnChanges: true,
  },
  {
    id: "std-build-check",
    sortOrder: 6,
    parallelGroup: null,
    name: "Onsite build check",
    kind: "confirmation",
    approverType: "role",
    approverRole: "ops",
    approverUserId: null,
    conditions: ["always"],
    slaDays: 0,
    invalidateOnNewVersion: false,
    restartFromHereOnChanges: true,
  },
];
